//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_MTY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetBusiness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetBusiness()
        {
            this.AspNetBusinessUsers = new HashSet<AspNetBusinessUser>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetBusinessUser> AspNetBusinessUsers { get; set; }
    }
}
